FROM node:12

COPY [".npmrc", "package.json", "package-lock.json", "/home/"]
WORKDIR /home/

ARG NPM_TOKEN
RUN npm install

# NODE_ENV=production environment must be set before building next app
ENV NODE_ENV=production

COPY . /home
RUN npm run build > build.log
RUN base64 -w 0 build.log

ARG PORT=3000
ARG AZURE_STORAGE_ACCOUNT
ARG AZURE_STORAGE_ACCESS_KEY
ARG UNIFORM_DATA_URL
ARG UNIFORM_API_URL
ARG UNIFORM_API_TOKEN
ARG UNIFORM_PUBLISH_AZUREBLOB_PUBLIC_URL

ENV PORT="${PORT}" \
    AZURE_STORAGE_ACCOUNT="${AZURE_STORAGE_ACCOUNT}" \    
    AZURE_STORAGE_ACCESS_KEY="${AZURE_STORAGE_ACCESS_KEY}" \
    UNIFORM_DATA_URL="${UNIFORM_DATA_URL}" \
    UNIFORM_API_URL="${UNIFORM_API_URL}" \
    UNIFORM_API_TOKEN="${UNIFORM_API_TOKEN}" \
    UNIFORM_PUBLISH_AZUREBLOB_PUBLIC_URL="${UNIFORM_PUBLISH_AZUREBLOB_PUBLIC_URL}" \
    AZCOPY_PATH="/home/azcopy"

# allow execution of azcopy
RUN chmod +x /home/azcopy

EXPOSE ${PORT}

CMD [ "node", "server.js" ]
